### ISSUE TITLE
Vnum, getlabel, step

### ISSUE THREAD

**Issue by Lindisse** [nstockton/tintin-mume#1]
Hello Nstockton,

As discussed yesterday, I made some little enhancements of the mapper proxy that I wish you could include:

- To may trigger actions, vnum prints "Vnum: 123".
- The command getlabel prints the label of the current room, if it exists.
- The command step moves the player by one room toward a destination. Actually, to implement this command, I added the variable self.autoWalk, which is only set to true by the run command.

I managed to make a git patch, but I do not how how to send patches on github... Please, tell me how to do.

Kind Regards,
Lindisse.

**Comment by nstockton** [comment]
Hello,
Thank you for the contribution. After reviewing the code, I have merged in your patch, and credited you in the commit log. I did change one thing however. 'getlabel' will now return all the labels that point to a room, not just the first one found. It will also optionally except a vnum as an argument for the target room. If no vnum is supplied, the current room's vnum will be used as you would expect.
In regards to using GitHub from the command line, I suggest you have a look at the [Hub CLI Utility.](https://github.com/github/hub "Hub CLI GitHub page") You can use it to create pull requests from forks that you've made.
Please note that any future issues or pull requests regarding the mapper should be sent to the [Mapper Proxy Mume repository](https://github.com/nstockton/mapperproxy-mume "Mapper Proxy Mume GitHub page") instead of this repository.
