### ISSUE TITLE
keyboard input not showing up

### ISSUE THREAD

**Issue by svesely** [nstockton/tintin-mume#2]
This is very odd, and I'm not convinced that it's not something I'm doing- but when typing in game my input isn't displayed. The commands are definitely being sent, and if I hit enter I do get the correct response, but I am unable to see what I'm typing.

I've tried compiling the tt++ beta from source, and cloned a clean copy of your (incredibly helpful) scripts to make sure it's not my hacky additions. Still no luck. 

I'm running on MacOS 10.14.2 via iTerm 3.2.7beta. I've played with changing the command color, switching echo on and off, and editing the prompt settings. Any suggestions?

**Comment by nstockton** [comment]
Hello there,

Are you by any chance trying to run the scripts with MMapper? If so, can you open scripts/main.tin and search for the following line.
```
#send {\xFF\xFD\x01};
```
Then comment the line out by changing it to:
```
#nop {#send {\xFF\xFD\x01}};
```
Does that fix your problem?
The reason I ask is that due to a long standing bug with the mume server, the server fails to negotiate character echo back on after it is turned off for password input. That line manually tells mume to turn character echo back on, but if you're using MMapper, turning character echo back on is handled by it instead. This would probably result in that line turning character echo off if used in conjunction with MMapper.

Fair warning if you're using the scripts in conjunction with MMapper, the scripts were originally written to be used by blind and low vision players in conjunction with the textual mapper proxy which allows for path finding and auto walking. Some of the functionality depends on the mapper proxy being used instead of MMAPPER. So if you use MMapper, you might find that some of the scripts fail to work as advertised. Also, I created this project a few years back for some blind players that used Linux because they needed a console based client for accessibility under Linux. Those players have long since moved on to other muds, so I haven't updated any of the scripts in this repository for a very long time. I still push updates to the mapper proxy to this repository though, in case those people ever decide to play Mume again, but for the last few years my focus has been on my MushClient scripts, as MushClient and my scripts for it are what I and all but 1 of the remaining blind players use.

I'm very happy if you find the scripts useful, just wanted to let you know I  probably won't be pushing a lot of updates to the TinTin script files in future.

**Comment by svesely** [comment]
That worked like a charm! Thank you so much! Also, thanks for the heads-up about the maintenance. It was awesome that you were helping folks out, and I'm really glad to have your scripts as a jumping-off point for making my own client addons.

I'm intrigued by the textual mapper. My experience with MUDs in general, and even Mume specifically, is almost negligible. I've found MMapper to be helpful, but now I'm curious what other tools are out there.

Thanks again!

**Comment by nstockton** [comment]
Glad it worked for you. Feel free to say hi in game. I'm on most nights as Dent.
